### PR TITLE
fix: don't discard error in client

### LINKED ISSUE #9: `useAsyncQuery` doesn't set `error` in lazy component
Here reproduction: https://stackblitz.com/edit/github-ryfoyv?file=components/UserInfo.vue
Query calls in `UserInfo.vue`. This component is not rendered until the user has performed a specific action.
But after rendering, the variable `error` remains `null`

### PR DESCRIPTION
**Pull request by littlejon85**
This resolves #9  
The main issue is that the client tries to use `serverError` from `useState` and ignores the `error` from `useAsyncData`.  
I'm not exactly sure how `serverError` is populated. I assume it has something to do with SSR. However in case without SSR the returned error is always `null`.

The proposed solution is to use the error from `useAsyncData` as initial value for `useState`.  
```ts
const serverError = useState<TError | null>(`error-${key}`, () => error.value)
```

### CODE REVIEW

**Comment by wobsoriano** [comment]
I'll test this locally. Thanks!

File: src/runtime/client.ts [hunk 1]
```diff
@@ -51,16 +51,13 @@ export async function useAsyncQuery<
...
     key,
     () => $client.query(...pathAndInput),
     // @ts-expect-error: Internal
     options,
-  )
-
-  if (process.server && error.value && !serverError.value)
-    serverError.value = error.value as any
+    )
+  const serverError = useState<TError | null>(`error-${key}`, () => error.value)
```
Comment (wobsoriano) [inline src/runtime/client.ts:60]: Getting `nuxt instance unavailable` when trying this locally.

Probably related to https://github.com/nuxt/framework/issues/6996

Comment (littlejon85) [reply src/runtime/client.ts]: Guess that's related to SSR.  
I reverted the changes and  removed `process.server` on line 62 to achieve the same effect. The error in playground should be gone now.
